/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace RaftRPC
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class VoteBackStruct : TBase
  {
    private int _term;
    private bool _voteGranted;

    public int Term
    {
      get
      {
        return _term;
      }
      set
      {
        __isset.term = true;
        this._term = value;
      }
    }

    public bool VoteGranted
    {
      get
      {
        return _voteGranted;
      }
      set
      {
        __isset.voteGranted = true;
        this._voteGranted = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool term;
      public bool voteGranted;
    }

    public VoteBackStruct() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Term = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Bool) {
                VoteGranted = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("VoteBackStruct");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.term) {
          field.Name = "term";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Term);
          oprot.WriteFieldEnd();
        }
        if (__isset.voteGranted) {
          field.Name = "voteGranted";
          field.Type = TType.Bool;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(VoteGranted);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("VoteBackStruct(");
      bool __first = true;
      if (__isset.term) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Term: ");
        __sb.Append(Term);
      }
      if (__isset.voteGranted) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("VoteGranted: ");
        __sb.Append(VoteGranted);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
