/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace RaftRPC
{
  public enum NodeRole
  {
    Follower = 1,
    Candidate = 2,
    Leader = 3,
  }
}
